---
language: ruby
bundler_args: --without development
script: ["bundle exec rake validate", "bundle exec rake lint", "bundle exec fakeroot rake spec SPEC_OPTS='--format documentation'", "bundle exec rake metadata"]
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  allow_failures:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
notifications:
  email: false
deploy:
  provider: puppetforge
  user: camptocamp
  password:
    secure: "WDjCKaby/VWxv6E3mIwGwMFbh/wPTvhxMy3uvabgpw3hLYRXgfkLqOSm+IpmRx4xAXnpyg8xizTTMY++7GbbLzUADUawAGHPuNHKgSCFW4E5clvcQ4RTHGgiCH1qisDwhnssYwYBH9YAcgWu6UHawxFDPRz9I13Kv+nRr8d49f0="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
